language: go

os: linux

dist: xenial

go:
- "1.15"
env:
  - GO111MODULE=on
before_install:
  - wget https://github.com/v2fly/v2ray-core/archive/v4.33.0.tar.gz && tar -zxvf  v4.33.0.tar.gz -C $GOPATH/src/github.com/GopherTy
before_script:
  - go install github.com/rakyll/statik
script:
  - ./build.sh s view 
  - ./build.sh l 
